framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session:
        #enabled: true
        handler_id: null
        #storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true

    csrf_protection: ~

    assets:
        version_strategy: 'App\Asset\VersionStrategy\CurrentVersionStrategy'
