---
{
   "kind": "pipeline",
   "name": "php:7.4 mariadb:10.5",
   "services": [
      {
         "environment": {
            "MYSQL_DATABASE": "planningb",
            "MYSQL_PASSWORD": "plb",
            "MYSQL_ROOT_PASSWORD": "rootplb",
            "MYSQL_USER": "plb"
         },
         "image": "mariadb:10.5",
         "name": "db"
      }
   ],
   "steps": [
      {
         "commands": [
            "apt update",
            "apt install -y libzip-dev",
            "docker-php-ext-install zip",
            "docker-php-ext-install mysqli",
            "docker-php-ext-install pdo_mysql",
            "cp .drone/.env.test.local .env.test.local",
            "cp .drone/.env.local .env.local",
            ".drone/install-composer.sh",
            "php composer.phar install -n --prefer-dist",
            "cp $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini && echo \"xdebug.mode=coverage\" | tee -a $PHP_INI_DIR/php.ini",
            "./vendor/bin/simple-phpunit --coverage-text --coverage-clover coverage.xml --bootstrap tests/bootstrap.php tests/"
         ],
         "image": "php:7.4",
         "name": "test"
      }
   ],
   "type": "docker"
}
---
{
   "kind": "pipeline",
   "name": "php:7.4 mysql:8.0",
   "services": [
      {
         "environment": {
            "MYSQL_DATABASE": "planningb",
            "MYSQL_PASSWORD": "plb",
            "MYSQL_ROOT_PASSWORD": "rootplb",
            "MYSQL_USER": "plb"
         },
         "image": "mysql:8.0",
         "name": "db"
      }
   ],
   "steps": [
      {
         "commands": [
            "apt update",
            "apt install -y libzip-dev",
            "docker-php-ext-install zip",
            "docker-php-ext-install mysqli",
            "docker-php-ext-install pdo_mysql",
            "cp .drone/.env.test.local .env.test.local",
            "cp .drone/.env.local .env.local",
            ".drone/install-composer.sh",
            "php composer.phar install -n --prefer-dist",
            "cp $PHP_INI_DIR/php.ini-development $PHP_INI_DIR/php.ini && echo \"xdebug.mode=coverage\" | tee -a $PHP_INI_DIR/php.ini",
            "./vendor/bin/simple-phpunit --coverage-text --coverage-clover coverage.xml --bootstrap tests/bootstrap.php tests/"
         ],
         "image": "php:7.4",
         "name": "test"
      }
   ],
   "type": "docker"
}
